# NGINX Cook Book 74p
# [STEP 1] ansible-playbook -i ./keys/inventory.txt ./ansible/install/nginx/nginx-install.yml

- name: NGINX Install by apt
  hosts: all
  become: True
  tasks:
    - name: Install NGINX
      shell: |
        apt update
        apt install nginx -y